name: 'cads_cds'
services:
  localstack:
    container_name: "cds-localstack-emulator"
    image: localstack/localstack:3.0.2
    ports:
      - '4568:4566'
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: [ 'CMD', 'curl', 'http://cds-localstack-emulator:4566/health' ]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - cdp-tenant

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - 16543:80
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
      - "./pgadmin-data:/var/lib/pgadmin"
    networks:
      - cdp-tenant

  redis:
    container_name: "cds-redis"
    image: redis:7.2.3-alpine3.18
    ports:
      - '6381:6379'
    restart: always
    networks:
      - cdp-tenant

  cads_cds:
    container_name: "cads_cds"
    platform: linux
    image: cads_cds
    build: ./
    ports:
      - '5555:5555'
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 5555
      LOCALSTACK_ENDPOINT: http://cds-localstack-emulator:4566
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    name: cdp-tenant
